spring.application.name=backend
spring.datasource.url=postgresql://neondb_owner:npg_au8lfM1KSyRk@ep-fancy-violet-acq2n7ur-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_au8lfM1KSyRk

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
